import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#e5e2e1',
        'on-surface': '#e5e2e1',
        outline: '#999077',
        'surface-container-high': '#2a2a2a',
        'primary-fixed': '#ffe16d',
        'on-primary-fixed': '#221b00',
        'surface-bright': '#3a3939',
        'surface-container-low': '#1c1b1b',
        'on-secondary': '#442b04',
        'on-secondary-fixed': '#291800',
        background: '#131313',
        'secondary-container': '#60441b',
        'error-container': '#93000a',
        secondary: '#e8c08c',
        'on-error': '#690005',
        'tertiary-fixed': '#79f5ff',
        'surface-variant': '#353534',
        'on-background': '#e5e2e1',
        'outline-variant': '#4d4732',
        'primary-container': '#ffd700',
        primary: '#fff6df',
        'secondary-fixed': '#ffddb3',
        'primary-fixed-dim': '#e9c400',
        'on-secondary-container': '#d9b27f',
        'secondary-fixed-dim': '#e8c08c',
        error: '#ffb4ab',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-fixed': '#002022',
        'surface-dim': '#131313',
        'on-error-container': '#ffdad6',
        'on-surface-variant': '#d0c6ab',
        'surface-container-highest': '#353534',
        'inverse-primary': '#705d00',
        'on-primary-container': '#705e00',
        'tertiary-container': '#00f1ff',
        'on-tertiary': '#00363a',
        'inverse-on-surface': '#313030',
        'on-primary': '#3a3000',
        'tertiary-fixed-dim': '#00dbe8',
        'on-secondary-fixed-variant': '#5d4219',
        'on-tertiary-fixed-variant': '#004f54',
        'on-tertiary-container': '#006a70',
        'on-primary-fixed-variant': '#544600',
        'surface-tint': '#e9c400',
        surface: '#131313',
        tertiary: '#defcff',
        'surface-container': '#201f1f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
